// Ordered list of source files (relative to src/) to concatenate for the
// zero-build browser preview. Order matters: a file may only reference
// names declared in files that appear before it in this list.
module.exports = [
  'types/index.ts',
  'theme/tokens.ts',
  'data/mockData.ts',
  'lib/router.tsx',
  'lib/store.tsx',
  'components/icons/index.tsx',

  'components/ui/Button.tsx',
  'components/ui/Badge.tsx',
  'components/ui/Card.tsx',
  'components/ui/MetricCard.tsx',
  'components/ui/Tabs.tsx',
  'components/ui/Modal.tsx',
  'components/ui/FormField.tsx',
  'components/ui/EmptyState.tsx',
  'components/ui/Toast.tsx',
  'components/ui/PaletteCard.tsx',
  'components/ui/TemplateCard.tsx',
  'components/ui/PhonePreview.tsx',
  'components/ui/ScheduleTimeline.tsx',
  'components/ui/GalleryGrid.tsx',
  'components/ui/MusicPlayer.tsx',
  'components/ui/QRPassCard.tsx',
  'components/ui/RSVPForm.tsx',
  'components/ui/InvitationCard.tsx',
  'components/ui/GuestCard.tsx',
  'components/ui/CountdownTimer.tsx',

  'components/marketing/MarketingNav.tsx',
  'components/marketing/MarketingFooter.tsx',

  'components/creator/Sidebar.tsx',
  'components/creator/Topbar.tsx',
  'components/creator/CreatorShell.tsx',

  'components/guest/GuestNav.tsx',
  'components/guest/GuestTopbar.tsx',

  'pages/marketing/Homepage.tsx',
  'pages/marketing/FeaturesPage.tsx',
  'pages/marketing/TemplatesPage.tsx',
  'pages/marketing/PricingPage.tsx',

  'pages/dashboard/Dashboard.tsx',
  'pages/dashboard/MyInvitations.tsx',
  'pages/dashboard/wizard/WizardSteps.tsx',
  'pages/dashboard/wizard/NewInvitation.tsx',
  'pages/dashboard/InvitationOverview.tsx',
  'pages/dashboard/InvitationEditor.tsx',
  'pages/dashboard/InvitationGuests.tsx',
  'pages/dashboard/InvitationSeating.tsx',
  'pages/dashboard/InvitationQR.tsx',
  'pages/dashboard/InvitationAnalytics.tsx',
  'pages/dashboard/DashboardTemplates.tsx',
  'pages/dashboard/DashboardMedia.tsx',
  'pages/dashboard/DashboardGuests.tsx',
  'pages/dashboard/DashboardMusic.tsx',
  'pages/dashboard/DashboardQR.tsx',
  'pages/dashboard/DashboardSeating.tsx',
  'pages/dashboard/DashboardSettings.tsx',

  'pages/guest/GuestInvitation.tsx',
  'pages/guest/GuestRSVP.tsx',
  'pages/guest/GuestSchedule.tsx',
  'pages/guest/GuestGallery.tsx',
  'pages/guest/GuestQR.tsx',
  'pages/guest/GuestDashboard.tsx',

  'App.tsx',
];
